### ISSUE TITLE
Not all dots appearing on map

### ISSUE THREAD

**Issue by reve0716** [Chicago/opengrid#283] opened 2017-01-05 20:01 UTC
**Find Data Panel**
Crime with map Extent
Crime with no set boundary
When running a search in Find Data Panel… A total of 1000 points are not appearing on the grid, its cutting off sections where the map extent is trying to pull data and only displaying a handful of data points on the grid while the information box states that it’s a total of 1000 records on the grid. The behavior is off; the data is not centered on the map when plotting data on the grid. When I maneuver west or north on the grid the data doesn’t display within the map extent it displays at the bottom of it. It doesn’t show a total of 1000 data.
When I travel south on the grid the data seems fine and shows data points perceiving to add up to 1000 points. 

See Images below where data is at the bottom and a data bubble displays with no point on the grid. How the data differ in certain directions on the grid.

**Image One:**

![image](https://cloud.githubusercontent.com/assets/12734080/21690881/e9cf750c-d33b-11e6-89c5-fcad664ddcd5.png)

**Image Two:**

![image](https://cloud.githubusercontent.com/assets/12734080/21691294/8562eaac-d33d-11e6-8e15-444624626567.png)

Data points also disappears and reappears on the gird upon zooming in and out (This was a previous issue)

![image](https://cloud.githubusercontent.com/assets/12734080/21691423/1cc68b10-d33e-11e6-8a9b-4a2a93007528.png)

![image](https://cloud.githubusercontent.com/assets/12734080/21691457/385087dc-d33e-11e6-9fe4-fa0e5521a94e.png)

![image](https://cloud.githubusercontent.com/assets/12734080/21691478/4ca6a806-d33e-11e6-9667-2ea2a97baf88.png)

Data should be at the max of 1000 for Food Inspection Chicago
Food Inspection without boundary:
WHERE city in Chicago is only displaying 237 points on the grid
WHERE zip code in 60602 it displays 1000 data points

With No Filter returns 1000
With Map Extent returns 1000

Food Inspection with Map extent boundary:
WHERE city in Chicago is only displaying 31 points on the grid (165 with default map view)
WHERE zip code in 60602 it displays 1000 data points (with default view)

**Comment by PriyaDoIT** [comment] 2017-01-05 20:08
hi @reve0716 , sorry but can you split these to two different issues?  It's easier to track progress and assign items on a per-issue basis.  Thank You

**Comment by PriyaDoIT** [comment] 2017-01-06 14:53
Created a new issue #284 and removed from here.

**Comment by PriyaDoIT** [comment] 2017-01-20 17:45
can't reproduce.  closing issue

**Closed by PriyaDoIT** 2017-01-20 17:45 UTC
Labels: bug
