### ISSUE TITLE
Questions around "Info: 1000 record(s) found"

### ISSUE THREAD

**Issue by smarziano** [Chicago/opengrid#213] opened 2016-06-19 14:44 UTC
During the CUTGroup test, there were questions about why there were 1000 records found when doing a broad search. Testers were expecting there to be more records, and did not know why it was limited to a 1000. This did not match expectations.

If there are more than 1,000 records being displayed for these broad searches, I would recommend saying that (ex: "More than 1,000 records found...") and then maybe giving some hints to use the filters (Possible addition when doing #138). 

If only 1,000 records are displayed then I would see if there are any ways to tell users more about what they are looking at. One tester, for example, added the "Crimes - 2001 to present" dataset, but after clicking around the map saw that there was only data from year 2013. He was not sure why and nothing on OpenGrid gave him the context he was looking for.

**Comment by tomschenkjr** [comment] 2016-06-20 04:33
Referring to #156 as well.

**Comment by PriyaDoIT** [comment] 2016-06-20 17:26
Duplicate of #156 .  Need Rod to check if the text is hard coded or not.

**Closed by PriyaDoIT** 2016-06-20 17:26 UTC
Labels: CUTGroup, duplicate
